// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShop.Models;

#nullable disable

namespace MyShop.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20240212144335_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyShop.Models.Bicycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bicycles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Trek",
                            Color = "Black",
                            ImageFileName = "trek-fx1-black.jpg",
                            Model = "FX 1",
                            Price = 450.00m,
                            Type = "Hybrid",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Giant",
                            Color = "Red",
                            ImageFileName = "giant-tcr-red.jpg",
                            Model = "TCR Advanced Pro 1 Disc",
                            Price = 3500.00m,
                            Type = "Road",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Specialized",
                            Color = "Blue",
                            ImageFileName = "specialized-rockhopper-blue.jpg",
                            Model = "Rockhopper Expert 29",
                            Price = 1100.00m,
                            Type = "Mountain",
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Cannondale",
                            Color = "White",
                            ImageFileName = "cannondale-synapse-white.jpg",
                            Model = "Synapse Carbon 105",
                            Price = 2000.00m,
                            Type = "Road",
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Trek",
                            Color = "Green",
                            ImageFileName = "trek-marlin-green.jpg",
                            Model = "Marlin 5",
                            Price = 550.00m,
                            Type = "Mountain",
                            Year = 2022
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Giant",
                            Color = "Silver",
                            ImageFileName = "giant-escape-silver.jpg",
                            Model = "Escape 3",
                            Price = 400.00m,
                            Type = "Hybrid",
                            Year = 2023
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Specialized",
                            Color = "Black",
                            ImageFileName = "specialized-sirrus-black.jpg",
                            Model = "Sirrus X 3.0",
                            Price = 700.00m,
                            Type = "Hybrid",
                            Year = 2022
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Cannondale",
                            Color = "Orange",
                            ImageFileName = "cannondale-topstone-orange.jpg",
                            Model = "Topstone Carbon Lefty 3",
                            Price = 3000.00m,
                            Type = "Gravel",
                            Year = 2023
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Trek",
                            Color = "Blue",
                            ImageFileName = "trek-domane-blue.jpg",
                            Model = "Domane SL 5",
                            Price = 2500.00m,
                            Type = "Road",
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Giant",
                            Color = "Yellow",
                            ImageFileName = "giant-talon-yellow.jpg",
                            Model = "Talon 29 3",
                            Price = 700.00m,
                            Type = "Mountain",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
